# Generated by Django 5.0.6 on 2024-05-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeroports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('pays', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'aeroports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Avions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'avions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Compagnies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('pays_rattachement', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'compagnies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pistes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('longueur', models.IntegerField()),
            ],
            options={
                'db_table': 'pistes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypesAvions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=255)),
                ('modele', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('longueur_piste_necessaire', models.IntegerField()),
            ],
            options={
                'db_table': 'types_avions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vols',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilote', models.CharField(max_length=255)),
                ('date_heure_depart', models.DateTimeField()),
                ('date_heure_arrivee', models.DateTimeField()),
            ],
            options={
                'db_table': 'vols',
                'managed': False,
            },
        ),
    ]
