# Generated by Django 5.0.6 on 2024-06-01 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aeromanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vols',
            options={'managed': True},
        ),
    ]
