# Generated by Django 5.0.6 on 2024-06-03 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeromanager', '0002_alter_vols_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pistes',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='vols',
            name='aeroport_arrivee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vols_aeroport_arrivee_set', to='aeromanager.aeroports'),
        ),
        migrations.AddField(
            model_name='vols',
            name='aeroport_depart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aeromanager.aeroports'),
        ),
        migrations.AddField(
            model_name='vols',
            name='avion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aeromanager.avions'),
        ),
        migrations.AddField(
            model_name='vols',
            name='piste_arrivee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vols',
            name='piste_depart',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
