# Generated by Django 5.0.6 on 2024-06-03 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeromanager', '0003_alter_pistes_options_vols_aeroport_arrivee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pistes',
            name='aeroport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aeromanager.aeroports'),
        ),
        migrations.AlterField(
            model_name='vols',
            name='aeroport_arrivee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vols_aeroport_arrivee_set', to='aeromanager.aeroports'),
        ),
        migrations.AlterField(
            model_name='vols',
            name='aeroport_depart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vols_aeroport_depart_set', to='aeromanager.aeroports'),
        ),
    ]
